name:                programming
version:             0.1.0.0
github:              "isovector/programming"
license:             BSD-3-Clause
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2025 Sandy Maguire"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/programming#readme>

dependencies:
- base >= 4.7 && < 5
- free
- comonad
- QuickCheck
- checkers
- generic-arbitrary
- hspec
- recursion-schemes
- lens

language: GHC2021

default-extensions:
- DerivingStrategies
- DeriveAnyClass
- DerivingVia
- LambdaCase
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-orphans

library:
  source-dirs: src
